name: Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-project:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: Build Project
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.7

      - name: Build Project
        uses: threeal/cmake-action@v2.0.0
