name: Pipeline

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.cpp"
      - "**.hpp"
      - "**.h"
      - "**.c"

jobs:
  coding-style:
    name: Coding-style
    uses: ./.github/workflows/coding-style.yml

  compilation:
    name: Compilation
    uses: ./.github/workflows/compilation.yml
