name: Pipeline-gui

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.cpp"

jobs:
  coding-style:
    name: Coding-style
    uses: ./.github/workflows/coding-style.yml

  compilation:
    name: Compilation
    uses: ./.github/workflows/compilation.yml
