name: "r-type"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-CPP-500-PAR-5-1-rtype-edward.lalande.git"

jobs:
  push_to_mirror:
    name: "Push to mirror"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
